package com.scau.pojo;

public class Class {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_id
     *
     * @mbggenerated
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_name
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_describe
     *
     * @mbggenerated
     */
    private String classDescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated
     */
    public Class(){
    }

    public Class(String className, String classDescribe) {
        this.className = className;
        this.classDescribe = classDescribe;
    }

    public Class(Integer classId, String className, String classDescribe) {
        this.classId = classId;
        this.className = className;
        this.classDescribe = classDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_id
     *
     * @return the value of class.class_id
     *
     * @mbggenerated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_name
     *
     * @return the value of class.class_name
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_describe
     *
     * @return the value of class.class_describe
     *
     * @mbggenerated
     */
    public String getClassDescribe() {
        return classDescribe;
    }

    @Override
    public String toString() {
        return "Class{" +
                "classId=" + classId +
                ", className='" + className + '\'' +
                ", classDescribe='" + classDescribe + '\'' +
                '}';
    }
}