package com.scau.pojo;

public class File {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_id
     *
     * @mbggenerated
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_type
     *
     * @mbggenerated
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_discribe
     *
     * @mbggenerated
     */
    private String fileDiscribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_directory
     *
     * @mbggenerated
     */
    private String fileDirectory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_complete_path
     *
     * @mbggenerated
     */
    private String fileCompletePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_relative_path
     *
     * @mbggenerated
     */
    private String fileRelativePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_author
     *
     * @mbggenerated
     */
    private String fileAuthor;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbggenerated
     */
    public File(Integer fileId, String fileName, String fileType, String fileDiscribe, String fileDirectory, String fileCompletePath, String fileRelativePath, String fileAuthor) {
        this.fileId = fileId;
        this.fileName = fileName;
        this.fileType = fileType;
        this.fileDiscribe = fileDiscribe;
        this.fileDirectory = fileDirectory;
        this.fileCompletePath = fileCompletePath;
        this.fileRelativePath = fileRelativePath;
        this.fileAuthor = fileAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_id
     *
     * @return the value of file.file_id
     *
     * @mbggenerated
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_name
     *
     * @return the value of file.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_type
     *
     * @return the value of file.file_type
     *
     * @mbggenerated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_discribe
     *
     * @return the value of file.file_discribe
     *
     * @mbggenerated
     */
    public String getFileDiscribe() {
        return fileDiscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_directory
     *
     * @return the value of file.file_directory
     *
     * @mbggenerated
     */
    public String getFileDirectory() {
        return fileDirectory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_complete_path
     *
     * @return the value of file.file_complete_path
     *
     * @mbggenerated
     */
    public String getFileCompletePath() {
        return fileCompletePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_relative_path
     *
     * @return the value of file.file_relative_path
     *
     * @mbggenerated
     */
    public String getFileRelativePath() {
        return fileRelativePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_author
     *
     * @return the value of file.file_author
     *
     * @mbggenerated
     */
    public String getFileAuthor() {
        return fileAuthor;
    }
}