package com.scau.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

import com.scau.pojo.Class;
import com.scau.pojo.ClassExample;
import com.scau.pojo.ClassNumber;

@Repository
public interface ClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated
     */
    int countByExample(ClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated
     */
    int deleteByExample(ClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated
     */
    @Delete({
        "delete from class",
        "where class_id = #{classId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer classId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated
     */
    @Insert({
        "insert into class (class_id, class_name, ",
        "class_describe)",
        "values (#{classId,jdbcType=INTEGER}, #{className,jdbcType=VARCHAR}, ",
        "#{classDescribe,jdbcType=VARCHAR})"
    })
    int insert(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated
     */
    int insertSelective(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated
     */
    List<Class> selectByExample(ClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "class_id, class_name, class_describe",
        "from class",
        "where class_id = #{classId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Class selectByPrimaryKey(Integer classId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Class record, @Param("example") ClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Class record, @Param("example") ClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated
     */
    @Update({
        "update class",
        "set class_name = #{className,jdbcType=VARCHAR},",
          "class_describe = #{classDescribe,jdbcType=VARCHAR}",
        "where class_id = #{classId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Class record);

    List<ClassNumber> countClassNum();
}